#Configuraci\u00f3n de Base de Datos - Gestor de Incidencias
# Modifica estos valores seg\u00fan tu configuraci\u00f3n de MySQL
# La contrase\u00f1a se puede dejar vac\u00eda si MySQL no tiene contrase\u00f1a
#Mon Apr 06 14:20:19 CEST 2026
db.host=localhost
db.nombre=gestor_incidencias
db.password=tu_contrase\u00f1a
db.puerto=3306
db.usuario=root
